package fur

import "strings"

// Comprehensive emoji map - common emojis for CLI/terminal use
var emojiMap = map[string]string{
	// Smileys & People
	"smile":          "😄",
	"grin":           "😁",
	"joy":            "😂",
	"rofl":           "🤣",
	"wink":           "😉",
	"blush":          "😊",
	"heart_eyes":     "😍",
	"star_struck":    "🤩",
	"thinking":       "🤔",
	"raised_eyebrow": "🤨",
	"neutral":        "😐",
	"expressionless": "😑",
	"rolling_eyes":   "🙄",
	"grimacing":      "😬",
	"lying":          "🤥",
	"relieved":       "😌",
	"pensive":        "😔",
	"sleepy":         "😪",
	"drooling":       "🤤",
	"sleeping":       "😴",
	"mask":           "😷",
	"nerd":           "🤓",
	"sunglasses":     "😎",
	"clown":          "🤡",
	"cowboy":         "🤠",
	"sad":            "😞",
	"cry":            "😢",
	"sob":            "😭",
	"angry":          "😠",
	"rage":           "😡",
	"exploding_head": "🤯",
	"flushed":        "😳",
	"hot":            "🥵",
	"cold":           "🥶",
	"woozy":          "🥴",
	"dizzy":          "😵",
	"shushing":       "🤫",
	"zany":           "🤪",
	"monocle":        "🧐",
	"confused":       "😕",
	"worried":        "😟",
	"slight_frown":   "🙁",
	"frown":          "☹️",
	"open_mouth":     "😮",
	"hushed":         "😯",
	"astonished":     "😲",
	"scream":         "😱",
	"fearful":        "😨",
	"cold_sweat":     "😰",
	"disappointed":   "😞",
	"sweat":          "😓",
	"hugging":        "🤗",
	"yum":            "😋",
	"stuck_out_tongue": "😛",
	"money_mouth":    "🤑",
	"smirk":          "😏",
	"unamused":       "😒",

	// Gestures
	"wave":           "👋",
	"raised_hand":    "✋",
	"ok_hand":        "👌",
	"pinching":       "🤏",
	"victory":        "✌️",
	"crossed_fingers": "🤞",
	"love_you":       "🤟",
	"rock_on":        "🤘",
	"call_me":        "🤙",
	"point_left":     "👈",
	"point_right":    "👉",
	"point_up":       "👆",
	"point_down":     "👇",
	"middle_finger":  "🖕",
	"thumbsup":       "👍",
	"thumbsdown":     "👎",
	"fist":           "✊",
	"punch":          "👊",
	"clap":           "👏",
	"raised_hands":   "🙌",
	"open_hands":     "👐",
	"palms_up":       "🤲",
	"handshake":      "🤝",
	"pray":           "🙏",
	"writing":        "✍️",
	"nail_polish":    "💅",
	"selfie":         "🤳",
	"muscle":         "💪",
	"leg":            "🦵",
	"foot":           "🦶",
	"ear":            "👂",
	"nose":           "👃",
	"brain":          "🧠",
	"eyes":           "👀",
	"eye":            "👁️",
	"tongue":         "👅",
	"lips":           "👄",

	// Animals
	"cat":            "🐱",
	"dog":            "🐶",
	"mouse":          "🐭",
	"hamster":        "🐹",
	"rabbit":         "🐰",
	"fox":            "🦊",
	"bear":           "🐻",
	"panda":          "🐼",
	"koala":          "🐨",
	"tiger":          "🐯",
	"lion":           "🦁",
	"cow":            "🐮",
	"pig":            "🐷",
	"frog":           "🐸",
	"monkey":         "🐵",
	"chicken":        "🐔",
	"penguin":        "🐧",
	"bird":           "🐦",
	"eagle":          "🦅",
	"duck":           "🦆",
	"owl":            "🦉",
	"bat":            "🦇",
	"wolf":           "🐺",
	"horse":          "🐴",
	"unicorn":        "🦄",
	"bee":            "🐝",
	"bug":            "🐛",
	"butterfly":      "🦋",
	"snail":          "🐌",
	"shell":          "🐚",
	"beetle":         "🪲",
	"ant":            "🐜",
	"cricket":        "🦗",
	"spider":         "🕷️",
	"scorpion":       "🦂",
	"turtle":         "🐢",
	"snake":          "🐍",
	"lizard":         "🦎",
	"dragon":         "🐉",
	"dragon_face":    "🐲",
	"dinosaur":       "🦖",
	"whale":          "🐳",
	"dolphin":        "🐬",
	"fish":           "🐟",
	"shark":          "🦈",
	"octopus":        "🐙",
	"crab":           "🦀",
	"lobster":        "🦞",
	"shrimp":         "🦐",
	"squid":          "🦑",
	"elephant":       "🐘",
	"rhino":          "🦏",
	"hippo":          "🦛",
	"camel":          "🐫",
	"giraffe":        "🦒",
	"kangaroo":       "🦘",
	"gorilla":        "🦍",
	"sloth":          "🦥",
	"otter":          "🦦",
	"skunk":          "🦨",
	"flamingo":       "🦩",
	"peacock":        "🦚",
	"parrot":         "🦜",
	"swan":           "🦢",
	"dodo":           "🦤",
	"feather":        "🪶",

	// Nature
	"bouquet":        "💐",
	"cherry_blossom": "🌸",
	"rose":           "🌹",
	"wilted_flower":  "🥀",
	"hibiscus":       "🌺",
	"sunflower":      "🌻",
	"blossom":        "🌼",
	"tulip":          "🌷",
	"seedling":       "🌱",
	"tree":           "🌲",
	"palm_tree":      "🌴",
	"cactus":         "🌵",
	"herb":           "🌿",
	"shamrock":       "☘️",
	"clover":         "🍀",
	"maple_leaf":     "🍁",
	"fallen_leaf":    "🍂",
	"leaf":           "🍃",
	"mushroom":       "🍄",

	// Food
	"apple":          "🍎",
	"green_apple":    "🍏",
	"pear":           "🍐",
	"orange":         "🍊",
	"lemon":          "🍋",
	"banana":         "🍌",
	"watermelon":     "🍉",
	"grapes":         "🍇",
	"strawberry":     "🍓",
	"blueberries":    "🫐",
	"melon":          "🍈",
	"cherries":       "🍒",
	"peach":          "🍑",
	"mango":          "🥭",
	"pineapple":      "🍍",
	"coconut":        "🥥",
	"kiwi":           "🥝",
	"tomato":         "🍅",
	"avocado":        "🥑",
	"eggplant":       "🍆",
	"potato":         "🥔",
	"carrot":         "🥕",
	"corn":           "🌽",
	"hot_pepper":     "🌶️",
	"cucumber":       "🥒",
	"broccoli":       "🥦",
	"garlic":         "🧄",
	"onion":          "🧅",
	"peanuts":        "🥜",
	"bread":          "🍞",
	"croissant":      "🥐",
	"pretzel":        "🥨",
	"bagel":          "🥯",
	"pancakes":       "🥞",
	"waffle":         "🧇",
	"cheese":         "🧀",
	"meat":           "🥩",
	"bacon":          "🥓",
	"hamburger":      "🍔",
	"fries":          "🍟",
	"pizza":          "🍕",
	"hotdog":         "🌭",
	"sandwich":       "🥪",
	"taco":           "🌮",
	"burrito":        "🌯",
	"egg":            "🥚",
	"cooking":        "🍳",
	"salad":          "🥗",
	"popcorn":        "🍿",
	"butter":         "🧈",
	"salt":           "🧂",
	"spaghetti":      "🍝",
	"ramen":          "🍜",
	"soup":           "🍲",
	"curry":          "🍛",
	"sushi":          "🍣",
	"bento":          "🍱",
	"dumpling":       "🥟",
	"cookie":         "🍪",
	"cake":           "🎂",
	"cupcake":        "🧁",
	"pie":            "🥧",
	"chocolate":      "🍫",
	"candy":          "🍬",
	"lollipop":       "🍭",
	"donut":          "🍩",
	"ice_cream":      "🍨",
	"shaved_ice":     "🍧",
	"coffee":         "☕",
	"tea":            "🍵",
	"sake":           "🍶",
	"champagne":      "🍾",
	"wine":           "🍷",
	"cocktail":       "🍸",
	"beer":           "🍺",
	"beers":          "🍻",
	"clinking":       "🥂",
	"tumbler":        "🥃",
	"cup_straw":      "🥤",
	"bubble_tea":     "🧋",
	"juice":          "🧃",
	"milk":           "🥛",
	"honey":          "🍯",
	"baby_bottle":    "🍼",
	"fork_knife":     "🍴",
	"spoon":          "🥄",
	"chopsticks":     "🥢",

	// Activities & Sports
	"soccer":         "⚽",
	"basketball":     "🏀",
	"football":       "🏈",
	"baseball":       "⚾",
	"tennis":         "🎾",
	"volleyball":     "🏐",
	"rugby":          "🏉",
	"badminton":      "🏸",
	"ping_pong":      "🏓",
	"hockey":         "🏒",
	"cricket_game":   "🏏",
	"golf":           "⛳",
	"bow_arrow":      "🏹",
	"fishing":        "🎣",
	"boxing":         "🥊",
	"martial_arts":   "🥋",
	"running":        "🏃",
	"surfing":        "🏄",
	"swimming":       "🏊",
	"biking":         "🚴",
	"mountain_biking": "🚵",
	"climbing":       "🧗",
	"yoga":           "🧘",
	"meditation":     "🧘",
	"trophy":         "🏆",
	"medal":          "🏅",
	"gold_medal":     "🥇",
	"silver_medal":   "🥈",
	"bronze_medal":   "🥉",
	"video_game":     "🎮",
	"joystick":       "🕹️",
	"slot_machine":   "🎰",
	"dice":           "🎲",
	"puzzle":         "🧩",
	"chess":          "♟️",
	"dart":           "🎯",
	"bowling":        "🎳",
	"kite":           "🪁",
	"pool":           "🎱",
	"crystal_ball":   "🔮",
	"magic_wand":     "🪄",
	"teddy_bear":     "🧸",
	"pinata":         "🪅",
	"nesting_dolls":  "🪆",
	"art":            "🎨",
	"yarn":           "🧶",
	"thread":         "🧵",
	"sewing":         "🪡",

	// Travel & Places
	"car":            "🚗",
	"taxi":           "🚕",
	"bus":            "🚌",
	"trolley":        "🚎",
	"race_car":       "🏎️",
	"police_car":     "🚓",
	"ambulance":      "🚑",
	"fire_truck":     "🚒",
	"truck":          "🚚",
	"train":          "🚆",
	"metro":          "🚇",
	"tram":           "🚊",
	"station":        "🚉",
	"airplane":       "✈️",
	"helicopter":     "🚁",
	"rocket":         "🚀",
	"satellite":      "🛰️",
	"ufo":            "🛸",
	"ship":           "🚢",
	"sailboat":       "⛵",
	"speedboat":      "🚤",
	"anchor":         "⚓",
	"construction":   "🚧",
	"fuel":           "⛽",
	"traffic_light":  "🚦",
	"stop_sign":      "🛑",
	"bicycle":        "🚲",
	"scooter":        "🛴",
	"skateboard":     "🛹",
	"roller_skate":   "🛼",
	"motorcycle":     "🏍️",
	"house":          "🏠",
	"house_garden":   "🏡",
	"office":         "🏢",
	"post_office":    "🏣",
	"hospital":       "🏥",
	"bank":           "🏦",
	"hotel":          "🏨",
	"school":         "🏫",
	"factory":        "🏭",
	"castle":         "🏰",
	"stadium":        "🏟️",
	"tent":           "⛺",
	"mountain":       "⛰️",
	"snow_mountain":  "🏔️",
	"volcano":        "🌋",
	"camping":        "🏕️",
	"beach":          "🏖️",
	"desert":         "🏜️",
	"island":         "🏝️",
	"park":           "🏞️",
	"sunrise":        "🌅",
	"sunset":         "🌇",
	"night":          "🌃",
	"cityscape":      "🏙️",
	"bridge":         "🌉",
	"milky_way":      "🌌",
	"carousel":       "🎠",
	"ferris_wheel":   "🎡",
	"roller_coaster": "🎢",
	"fountain":       "⛲",

	// Objects
	"watch":          "⌚",
	"phone":          "📱",
	"laptop":         "💻",
	"keyboard":       "⌨️",
	"desktop":        "🖥️",
	"printer":        "🖨️",
	"computer_mouse": "🖱️",
	"trackball":      "🖲️",
	"cd":             "💿",
	"dvd":            "📀",
	"floppy":         "💾",
	"disk":           "💽",
	"camera":         "📷",
	"video_camera":   "📹",
	"movie_camera":   "🎥",
	"projector":      "📽️",
	"film":           "🎞️",
	"telephone":      "☎️",
	"pager":          "📟",
	"fax":            "📠",
	"tv":             "📺",
	"radio":          "📻",
	"microphone":     "🎤",
	"headphones":     "🎧",
	"speaker":        "🔊",
	"mute":           "🔇",
	"bell":           "🔔",
	"no_bell":        "🔕",
	"megaphone":      "📣",
	"loudspeaker":    "📢",
	"hourglass":      "⌛",
	"timer":          "⏱️",
	"stopwatch":      "⏲️",
	"alarm":          "⏰",
	"clock":          "🕐",
	"battery":        "🔋",
	"plug":           "🔌",
	"bulb":           "💡",
	"flashlight":     "🔦",
	"candle":         "🕯️",
	"fire_extinguisher": "🧯",
	"oil":            "🛢️",
	"money":          "💵",
	"dollar":         "💲",
	"credit_card":    "💳",
	"gem":            "💎",
	"ring":           "💍",
	"crown":          "👑",
	"lipstick":       "💄",
	"kiss":           "💋",
	"gift":           "🎁",
	"balloon":        "🎈",
	"tada":           "🎉",
	"confetti":       "🎊",
	"ribbon":         "🎀",
	"ticket":         "🎫",
	"admission":      "🎟️",
	"crystal":        "🔮",
	"prayer_beads":   "📿",
	"envelope":       "✉️",
	"email":          "📧",
	"inbox":          "📥",
	"outbox":         "📤",
	"package":        "📦",
	"mailbox":        "📫",
	"postbox":        "📮",
	"ballot_box":     "🗳️",
	"pencil":         "✏️",
	"pen":            "🖊️",
	"fountain_pen":   "🖋️",
	"paintbrush":     "🖌️",
	"crayon":         "🖍️",
	"memo":           "📝",
	"briefcase":      "💼",
	"folder":         "📁",
	"open_folder":    "📂",
	"dividers":       "🗂️",
	"calendar":       "📅",
	"tear_calendar":  "📆",
	"spiral_notepad": "🗒️",
	"spiral_calendar": "🗓️",
	"card_index":     "📇",
	"chart_up":       "📈",
	"chart_down":     "📉",
	"bar_chart":      "📊",
	"clipboard":      "📋",
	"pushpin":        "📌",
	"round_pushpin":  "📍",
	"paperclip":      "📎",
	"linked_paperclips": "🖇️",
	"straight_ruler": "📏",
	"triangular_ruler": "📐",
	"scissors":       "✂️",
	"card_file":      "🗃️",
	"file_cabinet":   "🗄️",
	"wastebasket":    "🗑️",
	"lock":           "🔒",
	"unlock":         "🔓",
	"lock_with_pen":  "🔏",
	"lock_with_key":  "🔐",
	"key":            "🔑",
	"old_key":        "🗝️",
	"hammer":         "🔨",
	"axe":            "🪓",
	"pick":           "⛏️",
	"hammer_wrench":  "🛠️",
	"dagger":         "🗡️",
	"sword":          "⚔️",
	"gun":            "🔫",
	"boomerang":      "🪃",
	"shield":         "🛡️",
	"wrench":         "🔧",
	"screwdriver":    "🪛",
	"nut_bolt":       "🔩",
	"gear":           "⚙️",
	"clamp":          "🗜️",
	"balance":        "⚖️",
	"link":           "🔗",
	"chains":         "⛓️",
	"hook":           "🪝",
	"toolbox":        "🧰",
	"magnet":         "🧲",
	"ladder":         "🪜",
	"test_tube":      "🧪",
	"petri_dish":     "🧫",
	"dna":            "🧬",
	"microscope":     "🔬",
	"telescope":      "🔭",
	"satellite_antenna": "📡",
	"syringe":        "💉",
	"drop_of_blood":  "🩸",
	"pill":           "💊",
	"adhesive_bandage": "🩹",
	"stethoscope":    "🩺",
	"door":           "🚪",
	"elevator":       "🛗",
	"mirror":         "🪞",
	"window":         "🪟",
	"bed":            "🛏️",
	"couch":          "🛋️",
	"chair":          "🪑",
	"toilet":         "🚽",
	"plunger":        "🪠",
	"shower":         "🚿",
	"bathtub":        "🛁",
	"mouse_trap":     "🪤",
	"razor":          "🪒",
	"lotion":         "🧴",
	"safety_pin":     "🧷",
	"broom":          "🧹",
	"basket":         "🧺",
	"roll_of_paper":  "🧻",
	"bucket":         "🪣",
	"soap":           "🧼",
	"bubbles":        "🫧",
	"toothbrush":     "🪥",
	"sponge":         "🧽",
	"fire_ext":       "🧯",
	"shopping_cart":  "🛒",
	"cigarette":      "🚬",
	"coffin":         "⚰️",
	"headstone":      "🪦",
	"urn":            "⚱️",
	"moyai":          "🗿",
	"placard":        "🪧",
	"id_card":        "🪪",

	// Symbols - Status & Indicators (CLI-focused)
	"check":          "✅",
	"white_check":    "✓",
	"x":              "❌",
	"cross":          "✗",
	"warning":        "⚠️",
	"danger":         "⛔",
	"no_entry":       "🚫",
	"prohibited":     "🚷",
	"stop":           "🛑",
	"info":           "ℹ️",
	"question":       "❓",
	"exclamation":    "❗",
	"bangbang":       "‼️",
	"interrobang":    "⁉️",
	"100":            "💯",
	"low_brightness": "🔅",
	"high_brightness": "🔆",
	"signal":         "📶",
	"vibration":      "📳",
	"mobile_off":     "📴",
	"recycle":        "♻️",
	"fleur_de_lis":   "⚜️",
	"trident":        "🔱",
	"name_badge":     "📛",
	"beginner":       "🔰",
	"o":              "⭕",
	"white_circle":   "⚪",
	"black_circle":   "⚫",
	"red_circle":     "🔴",
	"orange_circle":  "🟠",
	"yellow_circle":  "🟡",
	"green_circle":   "🟢",
	"blue_circle":    "🔵",
	"purple_circle":  "🟣",
	"brown_circle":   "🟤",
	"white_square":   "⬜",
	"black_square":   "⬛",
	"red_square":     "🟥",
	"orange_square":  "🟧",
	"yellow_square":  "🟨",
	"green_square":   "🟩",
	"blue_square":    "🟦",
	"purple_square":  "🟪",
	"brown_square":   "🟫",
	"black_small_square": "▪️",
	"white_small_square": "▫️",
	"black_medium_square": "◼️",
	"white_medium_square": "◻️",
	"diamond_orange": "🔶",
	"diamond_blue":   "🔷",
	"small_diamond_orange": "🔸",
	"small_diamond_blue":   "🔹",
	"up_triangle":    "🔺",
	"down_triangle":  "🔻",
	"diamond":        "💠",
	"radio_button":   "🔘",
	"white_check_box": "☑️",
	"checkbox":       "✅",

	// Arrows
	"arrow_up":       "⬆️",
	"arrow_down":     "⬇️",
	"arrow_left":     "⬅️",
	"arrow_right":    "➡️",
	"arrow_up_right": "↗️",
	"arrow_down_right": "↘️",
	"arrow_down_left": "↙️",
	"arrow_up_left":  "↖️",
	"arrow_up_down":  "↕️",
	"left_right":     "↔️",
	"leftwards":      "↩️",
	"rightwards":     "↪️",
	"arrow_heading_up": "⤴️",
	"arrow_heading_down": "⤵️",
	"arrows_clockwise": "🔃",
	"arrows_counterclockwise": "🔄",
	"back":           "🔙",
	"end":            "🔚",
	"on":             "🔛",
	"soon":           "🔜",
	"top":            "🔝",

	// Music & Sound
	"music":          "🎵",
	"notes":          "🎶",
	"studio_mic":     "🎙️",
	"level_slider":   "🎚️",
	"control_knobs":  "🎛️",
	"musical_score":  "🎼",
	"musical_keyboard": "🎹",
	"drum":           "🥁",
	"saxophone":      "🎷",
	"trumpet":        "🎺",
	"guitar":         "🎸",
	"banjo":          "🪕",
	"violin":         "🎻",
	"accordion":      "🪗",
	"long_drum":      "🪘",

	// Hearts & Love
	"heart":          "❤️",
	"orange_heart":   "🧡",
	"yellow_heart":   "💛",
	"green_heart":    "💚",
	"blue_heart":     "💙",
	"purple_heart":   "💜",
	"black_heart":    "🖤",
	"white_heart":    "🤍",
	"brown_heart":    "🤎",
	"pink_heart":     "🩷",
	"light_blue_heart": "🩵",
	"grey_heart":     "🩶",
	"broken_heart":   "💔",
	"two_hearts":     "💕",
	"revolving_hearts": "💞",
	"heartbeat":      "💓",
	"heartpulse":     "💗",
	"sparkling_heart": "💖",
	"cupid":          "💘",
	"heart_box":      "💝",
	"heart_decoration": "💟",
	"heart_exclamation": "❣️",
	"mending_heart":  "❤️‍🩹",
	"heart_on_fire":  "❤️‍🔥",

	// Weather & Celestial
	"sun":            "☀️",
	"sun_small_cloud": "🌤️",
	"sun_cloud":      "⛅",
	"sun_behind_cloud": "🌥️",
	"sun_rain":       "🌦️",
	"cloud":          "☁️",
	"cloud_rain":     "🌧️",
	"cloud_storm":    "⛈️",
	"cloud_lightning": "🌩️",
	"cloud_snow":     "🌨️",
	"snowflake":      "❄️",
	"snowman":        "☃️",
	"wind":           "🌬️",
	"cyclone":        "🌀",
	"rainbow":        "🌈",
	"umbrella":       "☔",
	"droplet":        "💧",
	"sweat_drops":    "💦",
	"ocean":          "🌊",
	"fog":            "🌫️",
	"moon":           "🌙",
	"new_moon":       "🌑",
	"waxing_crescent": "🌒",
	"first_quarter":  "🌓",
	"waxing_gibbous": "🌔",
	"full_moon":      "🌕",
	"waning_gibbous": "🌖",
	"last_quarter":   "🌗",
	"waning_crescent": "🌘",
	"crescent_moon":  "🌙",
	"new_moon_face":  "🌚",
	"first_quarter_face": "🌛",
	"last_quarter_face": "🌜",
	"full_moon_face": "🌝",
	"sun_face":       "🌞",
	"ringed_planet":  "🪐",
	"star":           "⭐",
	"star2":          "🌟",
	"stars":          "✨",
	"sparkles":       "✨",
	"comet":          "☄️",
	"fire":           "🔥",
	"flame":          "🔥",
	"zap":            "⚡",
	"lightning":      "⚡",
	"boom":           "💥",
	"collision":      "💥",
	"sparkle":        "❇️",

	// Time
	"hourglass_flowing": "⏳",
	"hourglass_done": "⌛",
	"watch2":         "⌚",
	"alarm_clock":    "⏰",
	"stopwatch2":     "⏱️",
	"timer_clock":    "⏲️",
	"mantelpiece_clock": "🕰️",

	// Books & Learning
	"book":           "📖",
	"books":          "📚",
	"notebook":       "📓",
	"ledger":         "📒",
	"page_facing_up": "📄",
	"page_curl":      "📃",
	"scroll":         "📜",
	"newspaper":      "📰",
	"rolled_up_newspaper": "🗞️",
	"bookmark_tabs":  "📑",
	"bookmark":       "🔖",
	"label":          "🏷️",
	"graduation_cap": "🎓",

	// Miscellaneous useful for CLI
	"white_flag":     "🏳️",
	"black_flag":     "🏴",
	"checkered_flag": "🏁",
	"triangular_flag": "🚩",
	"crossed_flags":  "🎌",
	"pirate_flag":    "🏴‍☠️",
	"rainbow_flag":   "🏳️‍🌈",
	"transgender_flag": "🏳️‍⚧️",
	"atm":            "🏧",
	"put_litter":     "🚮",
	"potable_water":  "🚰",
	"wheelchair":     "♿",
	"mens":           "🚹",
	"womens":         "🚺",
	"restroom":       "🚻",
	"baby_symbol":    "🚼",
	"wc":             "🚾",
	"passport_control": "🛂",
	"customs":        "🛃",
	"baggage_claim":  "🛄",
	"left_luggage":   "🛅",
	"sos":            "🆘",
	"new":            "🆕",
	"free":           "🆓",
	"ok":             "🆗",
	"cool":           "🆒",
	"up":             "🆙",
	"ng":             "🆖",
	"vs":             "🆚",
	"parking":        "🅿️",
	"a":              "🅰️",
	"b":              "🅱️",
	"ab":             "🆎",
	"o2":             "🅾️",
	"cl":             "🆑",
	"id":             "🆔",
	"registered":     "®️",
	"copyright":      "©️",
	"tm":             "™️",
	"hash":           "️#️⃣",
	"asterisk":       "*️⃣",
	"zero":           "0️⃣",
	"one":            "1️⃣",
	"two":            "2️⃣",
	"three":          "3️⃣",
	"four":           "4️⃣",
	"five":           "5️⃣",
	"six":            "6️⃣",
	"seven":          "7️⃣",
	"eight":          "8️⃣",
	"nine":           "9️⃣",
	"keycap_ten":     "🔟",
	"capital_abcd":   "🔠",
	"abcd":           "🔡",
	"symbols":        "🔣",
	"abc":            "🔤",
	"input_latin_uppercase": "🔠",
	"input_latin_lowercase": "🔡",
	"input_numbers":  "🔢",
	"input_symbols":  "🔣",
	"input_latin":    "🔤",

	// Tech/Dev specific
	"computer":       "💻",
	"terminal":       "💻",
	"server":         "🖥️",
	"debug":          "🐛",
	"robot":          "🤖",
	"alien":          "👽",
	"skull":          "💀",
	"ghost":          "👻",
	"poop":           "💩",
	"speech_balloon": "💬",
	"thought_balloon": "💭",
	"zzz":            "💤",
	"eye_speech":     "👁️‍🗨️",
	"left_speech":    "🗨️",
	"right_anger":    "🗯️",
	"speech":         "💬",
	"thought":        "💭",
}

// EnableEmoji enables emoji parsing in the default markup parser.
func EnableEmoji() {
	DefaultMarkupParser().EnableEmoji = true
}

// DisableEmoji disables emoji parsing in the default markup parser.
func DisableEmoji() {
	DefaultMarkupParser().EnableEmoji = false
}

// LookupEmoji returns the emoji for a name.
func LookupEmoji(name string) (string, bool) {
	value, ok := emojiMap[strings.ToLower(name)]
	return value, ok
}

// EmojiNames returns all known emoji names.
func EmojiNames() []string {
	names := make([]string, 0, len(emojiMap))
	for name := range emojiMap {
		names = append(names, name)
	}
	return names
}

// RegisterEmoji adds a custom emoji.
func RegisterEmoji(name, emoji string) {
	emojiMap[strings.ToLower(name)] = emoji
}

func replaceEmoji(text string) string {
	var out strings.Builder
	for i := 0; i < len(text); i++ {
		if text[i] != ':' {
			out.WriteByte(text[i])
			continue
		}
		start := i + 1
		end := start
		for end < len(text) && isEmojiNameChar(text[end]) {
			end++
		}
		if end > start && end < len(text) && text[end] == ':' {
			name := strings.ToLower(text[start:end])
			if value, ok := emojiMap[name]; ok {
				out.WriteString(value)
				i = end
				continue
			}
		}
		out.WriteByte(text[i])
	}
	return out.String()
}

func isEmojiNameChar(b byte) bool {
	return (b >= 'a' && b <= 'z') ||
		(b >= 'A' && b <= 'Z') ||
		(b >= '0' && b <= '9') ||
		b == '_' || b == '-' || b == '+'
}
